# Generated by Django 5.0.2 on 2024-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgames',
            name='tesera_name',
            field=models.CharField(max_length=1024, verbose_name='Название игры на Тесера'),
        ),
    ]
